import { Plugin } from '@/types/plugin';

export const plugins: Plugin[] = [
  // Getting Started
  {
    id: '1',
    name: 'Claude Code Essentials',
    description: 'Essential tools for daily development. Includes: Code explanation, debugging, documentation, PR enhancement, git workflows',
    icon: '🔬',
    category: 'ai-ml',
    tags: ['essentials', 'code', 'debugging', 'docs', 'git'],
    installCommand: '/plugin install claude-code-essentials',
  },

  // Complete Workflow Systems
  {
    id: '2',
    name: 'Full Stack Development',
    description: 'End-to-end feature implementation. Backend API → Frontend UI → Mobile → Testing → Security → Deployment',
    icon: '🧩',
    category: 'utilities',
    tags: ['fullstack', 'backend', 'frontend', 'mobile', 'testing', 'deployment'],
    installCommand: '/plugin install full-stack-development',
  },
  {
    id: '3',
    name: 'Security Hardening',
    description: 'Security auditing and compliance. OWASP scanning, penetration testing, code review, SOC2/HIPAA/GDPR compliance',
    icon: '🛡️',
    category: 'utilities',
    tags: ['security', 'owasp', 'pentest', 'compliance'],
    installCommand: '/plugin install security-hardening',
  },
  {
    id: '4',
    name: 'Data ML Pipeline',
    description: 'ML/AI development and MLOps. Data engineering → Model training → MLOps → LangChain/RAG → Deployment',
    icon: '⚡',
    category: 'ai-ml',
    tags: ['ml', 'ai', 'rag', 'langchain', 'mlops'],
    installCommand: '/plugin install data-ml-pipeline',
  },
  {
    id: '5',
    name: 'Incident Response',
    description: 'Production debugging and SRE. Diagnostics → Root cause analysis → Rollback → Post-mortem documentation',
    icon: '🚒',
    category: 'utilities',
    tags: ['sre', 'debug', 'oncall', 'rca'],
    installCommand: '/plugin install incident-response',
  },
  {
    id: '6',
    name: 'Performance Optimization',
    description: 'System profiling and optimization. Profiling → Query optimization → Caching → Scalability assessment',
    icon: '🚀',
    category: 'utilities',
    tags: ['performance', 'profiling', 'caching', 'scalability'],
    installCommand: '/plugin install performance-optimization',
  },
  {
    id: '7',
    name: 'Code Quality Review',
    description: 'Multi-perspective code analysis. Architecture → Security → Performance → Test coverage analysis',
    icon: '🔍',
    category: 'code-tools',
    tags: ['review', 'architecture', 'security', 'performance', 'tests'],
    installCommand: '/plugin install code-quality-review',
  },
  {
    id: '8',
    name: 'Legacy Modernization',
    description: 'Codebase modernization workflows. Framework migration → Dependency updates → Refactoring → Compatibility testing',
    icon: '🧱',
    category: 'utilities',
    tags: ['migration', 'refactor', 'compatibility', 'dependencies'],
    installCommand: '/plugin install legacy-modernization',
  },
  {
    id: '9',
    name: 'Multi-Platform Apps',
    description: 'Cross-platform development. Web (React/Next.js) → iOS (Swift) → Android (Kotlin) → Desktop coordination',
    icon: '📱',
    category: 'utilities',
    tags: ['react', 'nextjs', 'ios', 'android', 'desktop'],
    installCommand: '/plugin install multi-platform-apps',
  },
  {
    id: '10',
    name: 'CI/CD Automation',
    description: 'CI/CD pipeline configuration. GitHub Actions/GitLab CI → Progressive deployment → Canary releases → Monitoring',
    icon: '🔄',
    category: 'utilities',
    tags: ['cicd', 'github-actions', 'gitlab', 'deployment', 'monitoring'],
    installCommand: '/plugin install cicd-automation',
  },
  {
    id: '11',
    name: 'Agent Optimization',
    description: 'AI agent performance tuning. Prompt engineering → Multi-agent coordination → Context management',
    icon: '🧠',
    category: 'ai-ml',
    tags: ['agents', 'prompt', 'context', 'coordination'],
    installCommand: '/plugin install agent-optimization',
  },
  {
    id: '12',
    name: 'Documentation Generation',
    description: 'Technical documentation automation. OpenAPI specs → Mermaid diagrams → Tutorials → API references',
    icon: '📚',
    category: 'utilities',
    tags: ['docs', 'openapi', 'mermaid', 'tutorials'],
    installCommand: '/plugin install documentation-generation',
  },

  // Focused Development Kits
  {
    id: '13',
    name: 'API Development Kit',
    description: 'REST/GraphQL API development. API scaffolding → OpenAPI docs → Security scanning → Mocking → Validation',
    icon: '🌐',
    category: 'utilities',
    tags: ['api', 'graphql', 'openapi', 'mock', 'validation'],
    installCommand: '/plugin install api-development-kit',
  },
  {
    id: '14',
    name: 'Testing Quality Suite',
    description: 'Comprehensive testing workflows. TDD workflows → Test generation → Unit/integration/e2e → Quality gates',
    icon: '🧪',
    category: 'code-tools',
    tags: ['testing', 'tdd', 'e2e', 'coverage'],
    installCommand: '/plugin install testing-quality-suite',
  },
  {
    id: '15',
    name: 'Infrastructure DevOps',
    description: 'Container orchestration deployment. Kubernetes manifests → Docker optimization → Terraform IaC → Cost analysis',
    icon: '⚙️',
    category: 'utilities',
    tags: ['kubernetes', 'docker', 'terraform', 'cost'],
    installCommand: '/plugin install infrastructure-devops',
  },
  {
    id: '16',
    name: 'Development Utilities',
    description: 'Daily productivity tools. Refactoring → Dependency auditing → Error analysis → Standup automation',
    icon: '🛠️',
    category: 'utilities',
    tags: ['refactor', 'dependencies', 'errors', 'automation'],
    installCommand: '/plugin install development-utilities',
  },

  // Infrastructure & Operations
  {
    id: '17',
    name: 'Cloud Infrastructure',
    description: 'AWS/Azure/GCP architecture. Cloud design → Kubernetes → Terraform IaC → Hybrid cloud → Cost optimization',
    icon: '☁️',
    category: 'utilities',
    tags: ['cloud', 'aws', 'azure', 'gcp', 'kubernetes', 'terraform'],
    installCommand: '/plugin install cloud-infrastructure',
  },
  {
    id: '18',
    name: 'Database Operations',
    description: 'Database optimization and administration. Schema design → Query optimization → Migrations → PostgreSQL/MySQL/MongoDB',
    icon: '🗄️',
    category: 'database',
    tags: ['database', 'schema', 'postgres', 'mysql', 'mongodb'],
    installCommand: '/plugin install database-operations',
  },

  // Marketing & Business
  {
    id: '19',
    name: 'SEO Content Suite',
    description: 'SEO optimization toolkit. Content analysis → Keyword research → Meta optimization → E-E-A-T signals',
    icon: '🔎',
    category: 'utilities',
    tags: ['seo', 'content', 'keywords', 'meta', 'eeat'],
    installCommand: '/plugin install seo-content-suite',
  },
  {
    id: '20',
    name: 'Business Analytics',
    description: 'Business intelligence and metrics. KPI tracking → Financial reporting → Data-driven decision making',
    icon: '📈',
    category: 'utilities',
    tags: ['analytics', 'kpi', 'reporting', 'metrics'],
    installCommand: '/plugin install business-analytics',
  },
  {
    id: '21',
    name: 'HR & Legal Compliance',
    description: 'HR and legal documentation. HR policies → Legal templates → GDPR/SOC2/HIPAA compliance → Employment contracts',
    icon: '📄',
    category: 'utilities',
    tags: ['hr', 'legal', 'compliance', 'gdpr', 'soc2', 'hipaa'],
    installCommand: '/plugin install hr-legal-compliance',
  },
  {
    id: '22',
    name: 'Customer & Sales Automation',
    description: 'Customer relationship workflows. Support automation → Sales pipeline → Email campaigns → CRM integration',
    icon: '🤝',
    category: 'utilities',
    tags: ['crm', 'sales', 'email', 'automation'],
    installCommand: '/plugin install customer-sales-automation',
  },

  // Specialized Domains
  {
    id: '23',
    name: 'Blockchain & Web3',
    description: 'Blockchain and smart contract development. Solidity → Smart contracts → DeFi protocols → NFT platforms → Web3 apps',
    icon: '⛓️',
    category: 'utilities',
    tags: ['blockchain', 'web3', 'solidity', 'defi', 'nft'],
    installCommand: '/plugin install blockchain-web3',
  },
  {
    id: '24',
    name: 'Quantitative Trading',
    description: 'Financial modeling and algorithmic trading. Quant analysis → Trading strategies → Portfolio risk → Backtesting',
    icon: '📊',
    category: 'utilities',
    tags: ['trading', 'quant', 'risk', 'backtesting'],
    installCommand: '/plugin install quantitative-trading',
  },
  {
    id: '25',
    name: 'Payment Processing',
    description: 'Payment gateway integration. Stripe/PayPal integration → Checkout flows → Subscription billing → PCI compliance',
    icon: '💳',
    category: 'utilities',
    tags: ['payments', 'stripe', 'paypal', 'billing', 'pci'],
    installCommand: '/plugin install payment-processing',
  },
  {
    id: '26',
    name: 'Game Development',
    description: 'Unity and Minecraft development. Unity C# scripting → Minecraft Bukkit/Spigot plugins → Game mechanics',
    icon: '🎮',
    category: 'utilities',
    tags: ['unity', 'csharp', 'minecraft', 'spigot'],
    installCommand: '/plugin install game-development',
  },
  {
    id: '27',
    name: 'Accessibility Compliance',
    description: 'WCAG accessibility auditing. WCAG validation → Screen reader testing → Keyboard navigation → Inclusive design',
    icon: '♿',
    category: 'utilities',
    tags: ['wcag', 'a11y', 'accessibility', 'compliance'],
    installCommand: '/plugin install accessibility-compliance',
  },
];
