import { Plugin } from '@/types/plugin';

export const plugins: Plugin[] = [
  {
    id: '1',
    name: 'AI Code Review',
    description: 'Automated code review plugin with AI-powered suggestions for improvements and best practices.',
    icon: '🔬',
    category: 'ai-ml',
    featured: true,
    sponsored: false,
    official: false,
    verified: true,
    installCommand: '/plugin install ai-code-review',
    stars: 234,
    downloads: 5400,
    author: 'DevTools AI',
    tags: ['review', 'analysis', 'quality'],
  },
  {
    id: '2',
    name: 'Quick Search',
    description: 'Fast web search integration directly in Claude Code for documentation and references.',
    icon: '🔍',
    category: 'utilities',
    featured: true,
    sponsored: false,
    official: false,
    verified: true,
    installCommand: '/plugin install quick-search',
    stars: 189,
    downloads: 3200,
    author: 'Community',
    tags: ['search', 'docs', 'reference'],
  },
  {
    id: '3',
    name: 'Time Tracker',
    description: 'Track coding time and generate productivity reports for your projects.',
    icon: '⏰',
    category: 'utilities',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: '/plugin install time-tracker',
    stars: 156,
    author: 'Productivity Tools',
    tags: ['time', 'tracking', 'productivity'],
  },
  {
    id: '4',
    name: 'GitHub Integration',
    description: 'Connect Claude Code directly to your GitHub repositories for seamless workflow.',
    icon: '⚡',
    category: 'code-tools',
    featured: true,
    sponsored: true,
    official: true,
    verified: true,
    installCommand: '/plugin install github',
    stars: 512,
    downloads: 12500,
    author: 'Anthropic',
    tags: ['github', 'git', 'version-control'],
  },
  {
    id: '5',
    name: 'Database Explorer',
    description: 'Browse and query databases directly from Claude Code with SQL autocompletion.',
    icon: '🗄️',
    category: 'database',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: '/plugin install db-explorer',
    stars: 378,
    author: 'DevTools Inc',
    tags: ['database', 'sql', 'query'],
  },
  {
    id: '6',
    name: 'API Tester',
    description: 'Test REST APIs and GraphQL endpoints with built-in authentication support.',
    icon: '🌐',
    category: 'utilities',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: '/plugin install api-tester',
    stars: 267,
    author: 'API Tools',
    tags: ['api', 'testing', 'rest', 'graphql'],
  },
  {
    id: '7',
    name: 'Code Formatter Pro',
    description: 'Advanced code formatting with support for 50+ languages and custom rules.',
    icon: '✨',
    category: 'code-tools',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: '/plugin install formatter-pro',
    stars: 445,
    author: 'FormatJS',
    tags: ['formatter', 'prettier', 'lint'],
  },
  {
    id: '8',
    name: 'Docker Manager',
    description: 'Manage Docker containers and images directly from Claude Code interface.',
    icon: '🐳',
    category: 'utilities',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: '/plugin install docker-manager',
    stars: 321,
    author: 'Container Labs',
    tags: ['docker', 'containers', 'devops'],
  },
  {
    id: '9',
    name: 'Smart Docs',
    description: 'Generate comprehensive documentation automatically from your codebase.',
    icon: '📚',
    category: 'ai-ml',
    featured: true,
    sponsored: true,
    official: false,
    installCommand: '/plugin install smart-docs',
    stars: 689,
    author: 'AI Dev Tools',
    tags: ['docs', 'documentation', 'ai'],
  },
  {
    id: '10',
    name: 'Project Templates',
    description: 'Quick-start templates for React, Next.js, Vue, and 20+ other frameworks.',
    icon: '📦',
    category: 'templates',
    featured: true,
    sponsored: false,
    official: true,
    installCommand: '/plugin install templates',
    stars: 892,
    author: 'Anthropic',
    tags: ['templates', 'boilerplate', 'starter'],
  },
  {
    id: '11',
    name: 'Test Generator',
    description: 'Automatically generate unit and integration tests for your code.',
    icon: '🎭',
    category: 'code-tools',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: '/plugin install test-generator',
    stars: 234,
    author: 'Test Automation Co',
    tags: ['testing', 'unit', 'automation'],
  },
  {
    id: '12',
    name: 'Environment Manager',
    description: 'Securely manage environment variables and secrets across multiple projects.',
    icon: '🔐',
    category: 'utilities',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: '/plugin install env-manager',
    stars: 198,
    author: 'SecureOps',
    tags: ['env', 'secrets', 'security'],
  },
];
