import { Plugin } from '@/types/plugin';

export const plugins: Plugin[] = [
  {
    id: '1',
    name: 'Claude MCP Adviser',
    description: 'An MCP service designed for displaying HTML content for the most MCP server for your needs.',
    icon: '🤖',
    category: 'ai-ml',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/mcp-adviser',
    stars: 234,
    author: 'Claude Team',
    tags: ['mcp', 'assistant', 'tools'],
  },
  {
    id: '2',
    name: 'Serper MCP Server',
    description: 'A Server MCP Server for seamless search integration with powerful APIs.',
    icon: '🔍',
    category: 'utilities',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/serper-mcp',
    stars: 189,
    author: 'Community',
    tags: ['search', 'api', 'integration'],
  },
  {
    id: '3',
    name: 'Time Protocol',
    description: 'A Model Context Protocol server that provides timezone and time conversion capabilities.',
    icon: '⏰',
    category: 'utilities',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: 'npx @modelcontextprotocol/server-time',
    stars: 156,
    author: 'MCP Team',
    tags: ['time', 'timezone', 'conversion'],
  },
  {
    id: '4',
    name: 'GitHub Integration',
    description: 'Connect Claude Code directly to your GitHub repositories for seamless workflow.',
    icon: '⚡',
    category: 'code-tools',
    featured: true,
    sponsored: true,
    official: true,
    installCommand: 'npx @claudeai/github-mcp',
    stars: 512,
    author: 'Anthropic',
    tags: ['github', 'git', 'version-control'],
  },
  {
    id: '5',
    name: 'Database Explorer',
    description: 'Browse and query databases directly from Claude Code with SQL autocompletion.',
    icon: '🗄️',
    category: 'database',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/db-explorer',
    stars: 378,
    author: 'DevTools Inc',
    tags: ['database', 'sql', 'query'],
  },
  {
    id: '6',
    name: 'API Tester',
    description: 'Test REST APIs and GraphQL endpoints with built-in authentication support.',
    icon: '🌐',
    category: 'utilities',
    featured: true,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/api-tester',
    stars: 267,
    author: 'API Tools',
    tags: ['api', 'testing', 'rest', 'graphql'],
  },
  {
    id: '7',
    name: 'Code Formatter Pro',
    description: 'Advanced code formatting with support for 50+ languages and custom rules.',
    icon: '✨',
    category: 'code-tools',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/formatter-pro',
    stars: 445,
    author: 'FormatJS',
    tags: ['formatter', 'prettier', 'lint'],
  },
  {
    id: '8',
    name: 'Docker Manager',
    description: 'Manage Docker containers and images directly from Claude Code interface.',
    icon: '🐳',
    category: 'utilities',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/docker-manager',
    stars: 321,
    author: 'Container Labs',
    tags: ['docker', 'containers', 'devops'],
  },
  {
    id: '9',
    name: 'AI Code Review',
    description: 'Get AI-powered code reviews with suggestions for improvements and best practices.',
    icon: '🔬',
    category: 'ai-ml',
    featured: true,
    sponsored: true,
    official: false,
    installCommand: 'npx @claudeai/code-review',
    stars: 689,
    author: 'AI Dev Tools',
    tags: ['ai', 'review', 'analysis'],
  },
  {
    id: '10',
    name: 'Project Templates',
    description: 'Quick-start templates for React, Next.js, Vue, and 20+ other frameworks.',
    icon: '📦',
    category: 'templates',
    featured: true,
    sponsored: false,
    official: true,
    installCommand: 'npx @claudeai/templates',
    stars: 892,
    author: 'Anthropic',
    tags: ['templates', 'boilerplate', 'starter'],
  },
  {
    id: '11',
    name: 'Playwright Integration',
    description: 'Run and debug Playwright tests with visual feedback and smart assertions.',
    icon: '🎭',
    category: 'code-tools',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/playwright-mcp',
    stars: 234,
    author: 'Test Automation Co',
    tags: ['testing', 'e2e', 'playwright'],
  },
  {
    id: '12',
    name: 'Environment Manager',
    description: 'Securely manage environment variables and secrets across multiple projects.',
    icon: '🔐',
    category: 'utilities',
    featured: false,
    sponsored: false,
    official: false,
    installCommand: 'npx @claudeai/env-manager',
    stars: 198,
    author: 'SecureOps',
    tags: ['env', 'secrets', 'security'],
  },
];
